apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-ymlconfig
  namespace: {{ if .Values.global.app_namespace_bak }}{{ .Values.global.app_namespace_bak }}{{else}}{{ .Chart.Name }}{{end}}
data:
  es-yml-config: |-
    http.host: 0.0.0.0
    {{.Release.Name}}=======
    # Uncomment the following lines for a production cluster deployment
    # transport.host: 0.0.0.0
    # discovery.zen.minimum_master_nodes: 1