apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-apm-elasticsearch-svc
  namespace: {{ if .Values.namespace_bak }}{{ .Values.namespace_bak }}{{else}}{{ .Chart.Name }}{{end}}
  labels:
    dep: {{ .Chart.Name }}-apm-elasticsearch-svc
spec:
  type: NodePort
  ports:
  - name: p-9200
    port: 9200
    targetPort: es-9200
  - name: p-9300
    port: 9300
    targetPort: es-9300
  selector:
    app: {{ .Chart.Name }}-apm-elasticsearch-pod


