apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-dep
  namespace: {{ if .Values.app_namespace_bak }}{{ .Values.app_namespace_bak }}{{else}}{{ .Chart.Name }}{{end}}
spec:
  replicas: {{ .Values.apmElasticsearchReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-pod
      namespace: {{ if .Values.app_namespace_bak }}{{ .Values.app_namespace_bak }}{{else}}{{ .Chart.Name }}{{end}}
    spec:
      containers:
      - name: container
        image: {{ .Values.apmElasticsearchImageName }}:{{ .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        # securityContext:
        #   runAsUser: 1000
        # command: ["/bin/bash", "-c", "tail -f /etc/hosts"]
        ports:
        - name: es-9200
          containerPort: 9200
        - name: es-9300
          containerPort: 9300
        volumeMounts:
        - name: {{ .Chart.Name }}-ymlconfig
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: {{ .Chart.Name }}-jvmconfig
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options 
        - name: es-data
          mountPath: /usr/share/elasticsearch/config/data
      volumes:
      - name: {{ .Chart.Name }}-ymlconfig
        configMap:
          name: {{ .Chart.Name }}-ymlconfig
          items:
          - key: es-yml-config
            path: elasticsearch.yml
      - name: {{ .Chart.Name }}-jvmconfig
        configMap:
          name: {{ .Chart.Name }}-jvmconfig
          items:
          - key: es-jvm-config
            path: jvm.options
      - name: es-data
        persistentVolumeClaim:
          claimName: pvc

      # tolerations:
      # - key: "key"
      #   operator: "Equal"
      #   value: "test02"
      #   effect: "PreferNoSchedule"
