{{- $app_namespace_bak := .Values.global.app_namespace_bak }}
{{- $chartName := .Chart.Name }}
{{- $namespace := .Release.Namespace }}

{{- $apm_StorageServer := .Values.apm_StorageServer}}
{{- $apm_Capacity := .Values.apm_Capacity}}
{{- $apm_StoragePath := .Values.apm_StoragePath}}


{{- range .Values.volumenum }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ if $app_namespace_bak }}{{ $chartName }}-sc-{{ $namespace }}-{{ $app_namespace_bak }}-{{ .num }}{{ else }}{{ $chartName }}-sc-{{ $namespace }}-{{ .num }}{{ end }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
{{- end }}

---

{{- range .Values.volumenum }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ if $app_namespace_bak }}{{ $chartName }}-pv-{{ $namespace }}-{{ $app_namespace_bak }}-{{ .num }}{{ else }}{{ $chartName }}-pv-{{ $namespace }}-{{ .num }}{{ end }}
spec:
  capacity:
    storage: {{ $apm_Capacity }}
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ if $app_namespace_bak }}{{ $chartName }}-sc-{{ $namespace }}-{{ $app_namespace_bak }}-{{ .num }}{{ else }}{{ $chartName }}-sc-{{ $namespace }}-{{ .num }}{{ end }}
  nfs:
    {{- if $app_namespace_bak }}
    path: {{ $apm_StoragePath }}{{ $namespace }}/{{ $app_namespace_bak }}/{{ $chartName }}-{{ $chartName }}-ss-{{ .num }}
    {{- else }}
    path: {{ $apm_StoragePath }}{{ $namespace }}/{{ $chartName }}-{{ $chartName }}-ss-{{ .num }}
    {{- end }}


    server: {{ $apm_StorageServer }}
---
{{- end }}

---

{{- range .Values.volumenum }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $chartName }}-{{ $chartName }}-ss-{{ .num }}
  namespace: {{ $namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ $apm_Capacity }}
  storageClassName: {{ if $app_namespace_bak }}{{ $chartName }}-sc-{{ $namespace }}-{{ $app_namespace_bak }}-{{ .num }}{{ else }}{{ $chartName }}-sc-{{ $namespace }}-{{ .num }}{{ end }}
---
{{- end }}

# ---

# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: init-vl-s
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer

# --- 

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: init-vl-pv
# spec:
#   capacity:
#     storage: 10M
#   volumeMode: Filesystem 
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: init-vl-s
#   nfs: 
#     path: /nfsdata/elensAIO/zhitu/init
#     server: {{ .Values.apm_StorageServer }}

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: init-vl-c
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10M
#   storageClassName: init-vl-s

