apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    svc: {{ .Chart.Name }}-svc
spec:
  type: NodePort
  ports:
  - name: p8080
    port: 8080
  selector:
    app: {{ .Chart.Name }}-pod

