apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-pod
    spec:
      containers:
      - name: con
        image: registry.elensdata.com/zhice-apm/java:1.0.1
        imagePullPolicy: IfNotPresent

          
