apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    dep: {{ .Chart.Name }}-svc
spec:
  type: NodePort
  ports:
    - name: neo4j-h
      targetPort: p7474
      port: 7474
    - name: neo4j-b
      targetPort: p7687
      port: 7687
  selector:
    app: {{ .Chart.Name }}-neo4j