# Default values for apm-zhice-visual.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageWebVisual: registry.elensdata.com/zhice-apm/web-visual

ENV_ACTION_ADDVISUALDATA: ''

direction: 'top'

padding: '[54, 0, 0, 0]'

hidebar: false
