apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    svc: {{ .Chart.Name }}-svc
spec:
  type: NodePort
  ports:
    - port: {{ .Values.rabbitmq-port1 }}
      targetPort: rabbitmq-port1
      protocol: TCP
      name: http
    - port: {{ .Values.rabbitmq-port2 }}
      targetPort: rabbitmq-port2
      protocol: TCP
      name: http  
  selector:
    app: {{ .Chart.Name }}-pod
