apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    svc: {{ .Chart.Name }}-svc
spec:
  type: {{ .Values.apm_Service.type }}
  ports:
    - port: {{ .Values.rabbitmq_port1 }}
      targetPort: rabbitmq_port1
      protocol: TCP
      name: http
    - port: {{ .Values.rabbitmq_port2 }}
      targetPort: rabbitmq_port2
      protocol: TCP
      name: http  
  selector:
    app: {{ .Chart.Name }}-pod
