apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}-dep
  labels:
    app: {{ .Chart.Name }}-dep
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: {{ .Chart.Name }}-pod 
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-pod
    spec:
      containers:
        - name: con
          image: {{.Values.imageWebSystem}}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: system-port
              containerPort: 80
              protocol: TCP   
          volumeMounts:
            - mountPath:  '/html/config.js'
              name: js-config
              subPath: config.js 
            - mountPath:  '/usr/local/nginx/conf/nginx.conf'
              name: ng-config
              subPath:  nginx.conf  
      volumes:
        - name: js-config
          configMap:  
            name: {{ .Chart.Name }}-env-config
            items:
              - key: env-config
                path: 'config.js'  
        - name: ng-config
          configMap:  
            name: {{ .Chart.Name }}-nginx-config
            items:
              - key: env-config
                path: 'nginx.conf'
  