# Default values for apm-zhice-flowchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageWebFlowChart: registry.elensdata.com/zhice-apm/web-flow

ENV_OUTPUT_FLOW_LIST: ''

ENV_ACTION_IMPORT: ''

ENV_ACTION_FLOW: ''

direction: 'top'

padding: '[54, 0, 0, 0]'

hidebar: false

