# Default values for apm-zhice-data-clean.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageWebDataEtl: registry.elensdata.com/zhice-apm/web-dataetl

ENV_OUTPUT_DATA_LIST: ''

ENV_OUTPUT_DATA_DETAIL: ''

ENV_OUTPUT_TEMPLATE_LIST: ''

ENV_OUTPUT_TEMPLATE_DETAIL: ''

ENV_ACTION_ADD: ''

direction: 'top'

padding: '[54, 0, 0, 0]'

hidebar: false