apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-redis
    spec:
      containers:
      - name: con
        image: {{ .Values.redisimage }}:{{ .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis-port
          containerPort: 6379
      # tolerations:
      # - key: "key"
      #   operator: "Equal"
      #   value: "test02"
      #   effect: "PreferNoSchedule"
              