apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
  labels:
    app: mysql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql-pod
  template:
    metadata:
      labels:
        app: mysql-pod
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "MYSQL_ALLOW_EMPTY_PASSWORD"
              value: "true"
            - name: "testvar"
              value: {{ .Values.myint | quote}}
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP

