apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-dep
  labels:
    app: {{ .Chart.Name }}-dep
spec:
  replicas: {{ .Values.apmMysqlReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-pod
    spec:
      containers:
        - name: con
          image: {{ .Values.apmMysqlImage.repository }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: {{ .Values.mysqlrootpasswd | quote }}
          ports:
            - name: mysql-port
              containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: mysqldb
            - name: mysqldcnf
              mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
              subPath: mysqld.cnf
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: mysql-claim
        - name: mysqldcnf
          configMap:
            name: mysqldcnf
            items:
              - key: mysqldcnf-config
                path: mysqld.cnf
      # tolerations:
      #   - key: "key"
      #     operator: "Equal"
      #     value: "test02"
      #     effect: "PreferNoSchedule"


