apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-svc
spec:
  type: {{ .Values.apm_Service.type }}
  ports:
    - port: {{ .Values.apm_Service.port }}
      targetPort: mysql-port
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-pod
