apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    app: {{ .Chart.Name }}-svc
spec:
  type: {{ .Values.apmMysqlService.type }}
  ports:
    - port: {{ .Values.apmMysqlService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}-pod
