apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ if .Values.app_namespace_bak }}{{ .Chart.Name }}-pv-{{ .Values.app_namespace_bak }}{{ else }}{{ .Chart.Name }}-pv{{ end }}
spec:
  capacity:
    storage: {{ .Values.apm_Capacity }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ if .Values.app_namespace_bak }}{{ .Chart.Name }}-sc-{{ .Values.app_namespace_bak }}{{ else }}{{ .Chart.Name }}-sc{{ end }}
  nfs:
    {{- if .Values.app_namespace_bak }}
    path: {{ .Values.apm_StoragePath }}{{ .Values.app_namespace_bak }}/{{ .Chart.Name }}
    {{- else }}
    path: {{ .Values.apm_StoragePath }}{{ .Chart.Name }}
    {{- end }}
    server: {{ .Values.apm_StorageServer }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ if .Values.app_namespace_bak }}{{ .Chart.Name }}-sc-{{ .Values.app_namespace_bak }}{{ else }}{{ .Chart.Name }}-sc{{ end }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apm_Capacity }}
  storageClassName: {{ if .Values.app_namespace_bak }}{{ .Chart.Name }}-sc-{{ .Values.app_namespace_bak }}{{ else }}{{ .Chart.Name }}-sc{{ end }}
  