apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
spec:
  capacity:
    storage: {{ .Values.apmMysqlCapacity }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Chart.Name }}-sc
  nfs:
    path: {{ .Values.apmMysqlStoragePath }}
    server: {{ .Values.apmMysqlStorageServer }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apmMysqlCapacity }}
  storageClassName: {{ .Chart.Name }}-sc
