apiVersion: v1
kind: PersistentVolume
metadata:
  name: zhitu-mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysqlvolumespace }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zhitu-mysql-volume
  nfs:
    path: {{ .Values.mysqlvolumepvpath }}
    server: {{ .Values.volumeserver }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zhitu-mysql-volume
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysqlvolumespace }}
  storageClassName: zhitu-mysql-volume
