apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
  - host: {{ if .Values.global.app_host }}{{ .Values.global.app_host }}_{{ .Chart.Name }}{{ else }}{{ .Chart.Name }}{{ end }}.{{ .Values.global.domain }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ .Chart.Name }}-svc
          servicePort: 8370
