apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels: 
    svc: {{ .Chart.Name }}-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: template-port
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-pod