apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels: 
    dep:  {{ .Chart.Name }}-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: datasource-port
      # nodePort: 18771
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}-pod