apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    svc: {{ .Chart.Name }}-svc
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: unoconv-port
  selector:
    app: {{ .Chart.Name }}-pod

